product/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ItemList.as_view()),
    path('<int:pk>/', views.ItemDetail.as_view()),
    path('category/<str:slug>', views.category_page),
    path('manufacturer/<str:slug>', views.manufacturer_page),
    path('create_product', views.ItemCreate.as_view()),
    path('update_product/<int:pk>/', views.ItemUpdate.as_view()),
    path('<int:pk>/new_comment/', views.new_comment),
    path('search/<str:q>/', views.ItemSearch.as_view()),
]

shopping_mall/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('', include('single_pages.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.contrib.auth.models import User
from django.db import models
from markdown import markdown
from markdownx.models import MarkdownxField

# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.category_name

    def get_absolute_url(self):
        return f'/product/category/{self.slug}'

    class Meta:
        # admin 페이지에 모델 자동으로 뒤에 s 붙는거를 다음 문자열로 바꿔라...
        verbose_name_plural = 'Categories'

class Manufacturer(models.Model):
    manufacturer_name = models.CharField(max_length=50, unique=True)
    address = models.CharField(max_length=100, null=True)
    number = models.CharField(max_length=30, null=True)

    manufacturer_image = models.ImageField(upload_to='product/images/manufacturer/', blank=True)

    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.manufacturer_name

    def get_absolute_url(self):
        return f'/product/manufacturer/{self.slug}'

class Item(models.Model):
    title = models.CharField(max_length=30)
    content = MarkdownxField()
    image = models.ImageField(upload_to='product/images/Item/', blank=True)
    price = models.IntegerField()

    manufacturer = models.ForeignKey(Manufacturer, null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)

    kcal = models.CharField(max_length=30, null=True, blank=True)
    gram = models.CharField(max_length=30, null=True, blank=True)
    note = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'/product/{self.pk}/'

    def get_content_markdown(self):
        return markdown(self.content)

class Comment(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        return f'{self.item.get_absolute_url()}#comment-{self.pk}'


    def get_avatar_url(self):
        if self.author.socialaccount_set.exists() :
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return f'https://doitdjango.com/avatar/id/401/5c35620aec71444b/svg/{self.author.username}/'

product/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

product/views.py
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import CommentForm

from .models import Item, Category, Manufacturer


class ItemList(ListView):
    model = Item
    ordering = '-pk'
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ItemList,self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_item_count'] = Item.objects.filter(category=None).count()
        context['manufacturers'] = Manufacturer.objects.all()
        context['no_manufacturer_item_count'] = Item.objects.filter(manufacturer=None).count()
        return context

class ItemDetail(DetailView):
    model = Item

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ItemDetail,self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_item_count'] = Item.objects.filter(category=None).count()
        context['manufacturers'] = Manufacturer.objects.all()
        context['no_manufacturer_item_count'] = Item.objects.filter(manufacturer=None).count()
        context['comment_form'] = CommentForm
        return context

def category_page(request, slug):
    # 다대일
    category = Category.objects.get(slug=slug)
    return render(request, 'product/item_list.html',
           {
               'item_list': Item.objects.filter(category=category),
               'categories': Category.objects.all(),
               'manufacturers': Manufacturer.objects.all(),
               'no_category_item_count': Item.objects.filter(category=None).count(),
               'no_manufacturer_item_count': Item.objects.filter(manufacturer=None).count(),
               'category': category
           })

def manufacturer_page(request, slug):
    manufacturer = Manufacturer.objects.get(slug=slug)
    return render(request, 'product/item_list.html',
           {
               'item_list': Item.objects.filter(manufacturer=manufacturer),
               'categories': Category.objects.all(),
               'manufacturers': Manufacturer.objects.all(),
               'no_category_item_count': Item.objects.filter(category=None).count(),
               'no_manufacturer_item_count': Item.objects.filter(manufacturer=None).count(),
               'manufacturer': manufacturer
           })

class ItemCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Item
    fields = ['title', 'content', 'image', 'price', 'manufacturer', 'category', 'kcal', 'gram', 'note']

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            # 로그인한 유저이면 create product 가능하게...
            return super(ItemCreate, self).form_valid(form)
        else:
            return redirect('/product/')

class ItemUpdate(LoginRequiredMixin, UpdateView):
    model = Item
    fields = ['title', 'content', 'image', 'price', 'manufacturer', 'category', 'kcal', 'gram', 'note']
    template_name = 'product/item_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and (request.user.is_superuser or request.user.is_staff):
            return super(ItemUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

def new_comment(request, pk):
    if request.user.is_authenticated:
        item = get_object_or_404(Item, pk=pk)
        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.item = item
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else:
            return redirect(item.get_absolute_url())
    else:
        raise PermissionDenied

class ItemSearch(ItemList) :
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Item.objects.filter(
            Q(title__contains=q) | Q(content__contains=q)
        ).distinct()
        return post_list

    def get_context_data(self, **kwargs):
        context = super(ItemSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search : {q}({self.get_queryset().count()})'

        return context

product/templates/product/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<html>
<head>
    <title>{% block head_title %}20181038_Product page{% endblock %}</title>
    <link href="{% static 'product/bootstrap/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="screen">
    <link href="{% static 'product/css/product-item.css' %}" rel="stylesheet" type="text/css" media="screen">
    <link href="{% static 'product/css/back-image.css' %}" rel="stylesheet" type="text/css" media="screen">

    <script src="https://kit.fontawesome.com/768f9a0685.js" crossorigin="anonymous"></script>
</head>
<body>

{% include 'product/navbar.html' %}

<div class="container mt-3">
    <div class="row">
        <div class="col-md-8 col-lg-9">
            {% block main_area %}
            {% endblock %}
        </div>
        <div class="col-md-4 col-lg-3">
            <!-- Search widget-->
            <div class="card mb-4">
                <div class="card-header"><i class="fas fa-search"></i>&nbsp;Search</div>
                <div class="card-body">
                    <div class="input-group">
                        <input class="form-control" type="text" id="search-input" placeholder="Enter search term..."
                               aria-label="Enter search term..." aria-describedby="button-search"/>
                        <button class="btn btn-primary" id="button-search" type="button" onclick="searchItem()">Go!
                        </button>
                    </div>
                </div>
            </div>
            <!-- Categories widget-->
            <div class="card mb-4">
                <div class="card-header">Categories</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <ul>
                                {% for c in categories %}
                                <li><a href="{{c.get_absolute_url}}">{{ c }} ({{ c.item_set.count }})</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Manufacturer widget-->
            <div class="card mb-4">
                <div class="card-header">Manufacturers</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <ul>
                                {% for m in manufacturers %}
                                <li><a href="{{m.get_absolute_url}}">{{ m }} ({{ m.item_set.count }})</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div style="text-align:center">
                {% block product_plus %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>

<script>
            function searchItem(){
                let searchValue = document.getElementById('search-input').value.trim();
                if( searchValue.length > 1){
                    location.href = "/product/search/" + searchValue + "/";
                }
                else{
                    alert('검색어(' + searchValue + ')가 너무 짧습니다.');
                }
            };
            document.getElementById('search-input').addEventListener('keyup',
                function(event) {
                    if(event.key == 'Enter') {searchItem();}
                }
            );

</script>

{% include 'product/footer.html' %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>

</body>
</html>

product/templates/product/base_full_width.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<html>
<head>
    <title>{% block head_title %}20181038_Product page{% endblock %}</title>
    <link href="{% static 'product/bootstrap/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="screen">
    <link href="{% static 'product/css/product-item.css' %}" rel="stylesheet" type="text/css" media="screen">
    <link href="{% static 'product/css/back-image.css' %}" rel="stylesheet" type="text/css" media="screen">

    <script src="https://kit.fontawesome.com/768f9a0685.js" crossorigin="anonymous"></script>
</head>
<body>

{% include 'product/navbar.html' %}

<div class="container mt-3" style="padding-bottom: 50px">
    <div class="row">
        <div class="col-12" id="main-area">
            {% block main_area %}
            {% endblock %}
        </div>
    </div>
</div>

{% include 'product/footer.html' %}


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>

</body>
</html>

product/templates/product/footer.html
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container">
        <div class="row m-0 text-center text-white">
            <div class="col-lg-2"></div>
            <div class="col-lg-3">Copyright &copy; OH.HANNA</div>
            <div class="col-lg-2">대한민국 경기도</div>
            <div class="col-lg-2">TEL : 010.1234.5678</div>
            <div class="col-lg-2"></div>
        </div>
    </div>
</footer>

product/templates/product/item_detail.html
{% extends 'product/base.html' %}
{% load crispy_forms_tags %}

{% block product_plus %}
{% if user.is_authenticated %}
{% if user.is_staff or user.is_superuser %}
<a class="btn btn-dark btn-small" href="/product/update_product/{{ item.pk }}/">
    <i class="fas fa-pen"></i> Edit Product
</a>
{% endif %}
{% endif %}
{% endblock %}

{% block main_area %}
<!-- Post content-->
<div>
    <!-- Post header-->
    <header class="mb-4">
        <!-- Product title-->
        <h1 class="fw-bolder mb-1">{{ item.title }}</h1>
        <!-- Product categories-->
        {% if item.category %}
        <span class="badge badge-pill badge-info">{{ item.category }}</span>
        {% endif %}
        {% if item.manufacturer %}
        <span class="badge badge-pill badge-primary">{{ item.manufacturer }}</span>
        {% endif %}
        <p></p>
        {% if item.note %}
        <span class="badge badge-pill">{{ item.note }}</span>
        {% endif %}
        {% if item.gram %}
        <span class="badge badge-pill">1회 제공량 : {{ item.gram }}</span>
        {% endif %}
        {% if item.kcal %}
        <span class="badge badge-pill">{{ item.kcal }}</span>
        {% endif %}

    </header>
    <!-- Preview image figure-->
    <figure class="mb-4">
        {% if item.image %}
        <img class="img-fluid rounded" src="{{ item.image.url }}" height="500" width="500"/>
        {% else %}
        <img class="img-fluid rounded" src="https://picsum.photos/seed/{{item.id}}/500/500"/>
        {% endif %}
    </figure>
    <!-- Post content-->
    <section class="mb-5" style="font-weight: bold; background-color: white;">
            <p>{{ item.get_content_markdown | safe }}</p>
    </section>
</div>
<!-- Comments section-->
<div class="mb-5">
    <div class="card bg-light">
        <div class="card-body">
            <!-- Comment form-->
            {% if user.is_authenticated %}
                <form class="mb-4" id="comment-form" method="POST"
                      action="{{item.get_absolute_url}}new_comment/">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ comment_form | crispy }}
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            {% else %}
                <a role="button" class="btn btn-outline-dark" href="#"
                        data-toggle="modal" data-target="#loginModal">
                    Log in and leave a comment
                </a>
            {% endif %}
            <!-- Single comment-->
            {% if item.comment_set.exists %}
                {% for comment in item.comment_set.all %}
                <!-- Single comment -->
                    <div class="d-flex" id="comment-{{comment.pk}}">
                        <div class="flex-shrink-0">
                            <img class="rounded-circle" src="{{ comment.get_avatar_url }}"
                                 alt="{{ comment.get_avatar_url }}" width="60px"/>
                        </div> &nbsp;
                        <div class="ms-3">
                            <div class="fw-bold">- {{comment.author.username}} &nbsp;&nbsp;
                                <small class="text-muted"> {{comment.created_at}}</small></div>
                            <p>{{comment.content | linebreaks }}</p>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

product/templates/product/item_form.html
{% extends 'product/base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title %}20181038_Create Product{% endblock %}
{% block main_area %}
<h1>Create New Product</h1>
<hr/>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form | crispy }}
    <br>
    <button type="submit" class="btn btn-dark float-right">Submit</button>
</form>
{{ form.media }}
{% endblock %}

product/templates/product/item_list.html
{% extends 'product/base.html' %}

{% block product_plus %}
    {% if user.is_authenticated %}
        {% if user.is_staff or user.is_superuser %}
        <a class="btn btn-dark btn-small" href="/product/create_product">
            <i class="fas fa-pen"></i> New Product
        </a>
        {% endif %}
    {% endif %}
{% endblock %}

{% block main_area %}
<div class="col-md-8 col-lg-9">
    <h1>
        Product
        {% if category %}
        <span class="badge badge-pill badge-info">{{ category }}</span>
        {% endif %}
        {% if manufacturer %}
        <span class="badge badge-pill badge-primary">{{ manufacturer }}</span>
        {% endif %}
        {% if search_info %}
        <span class="badge badge-pill badge-warning">{{ search_info }}</span>
        {% endif %}
    </h1>
    {% if item_list.exists %}
        <!-- Blog post-->
        {% for p in item_list %}
            <div class="card mb-4">
                {% if p.image %}
                <img class="card-img-top" src="{{ p.image.url }}"/>
                {% else %}
                <img class="card-img-top" src="https://picsum.photos/seed/{{p.id}}/500/500" alt="random image"/>
                {% endif %}
                <div class="card-body">

                    {% if p.category %}
                    <span class="badge badge-pill badge-info float-right">{{ p.category }}</span>
                    {% endif %}

                    <h2 class="card-title h4">{{ p.title }}</h2>
                    <h5 class="text_muted">{{ p.price }} 원</h5>
                    <a class="btn btn-primary" href="{{ p.get_absolute_url }}">Read more →</a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h2>아직 게시물이 없습니다.</h2>
    {% endif %}
        <!-- Pagination-->
        {% if is_paginated %}
            <ul class="pagination justify-content-center my-4">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.previous_page_number}}" tabindex="-1" aria-disabled="true">&larr;
                        Newer</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" aria-disabled="true">&larr; Newer</a>
                </li>
                {% endif %}
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.next_page_number}}">Older &rarr;</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#!">Older &rarr;</a>
                </li>
                {% endif %}
            </ul>
        {% endif %}

</div>
{% endblock %}

product/templates/product/item_update_form.html
{% extends 'product/base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title %}20181038_Edit Product{% endblock %}
{% block main_area %}
<h1>Edit Product</h1>
<hr/>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form | crispy }}
    <button type="submit" class="btn btn-dark float-right">Submit</button>
</form>
{{ form.media }}
{% endblock %}

product/templates/product/navbar.html
{% load socialaccount %}
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/">Dessert Shopping Mall</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item"> <!-- class="active" -->
                    <a class="nav-link" href="/product/"><i class="fas fa-store"></i> Product <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/manufacturer_page/"><i class="far fa-building"></i>&nbsp;Manufacturer</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/my_page/"><i class="far fa-user"></i>&nbsp;My page</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {% if user.socialaccount_set.all.0.get_avatar_url %}
                        <img class="rounded-circle" width="25px"
                             src="{{user.socialaccount_set.all.0.get_avatar_url}}">
                      {% else %}
                        <img class="rounded-circle" width="25px"
                             src="https://doitdjango.com/avatar/id/401/5c35620aec71444b/svg/{{user.username}}/">
                      {% endif %}
                        {{user.username}}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a role="button" class="btn btn-primary" href="/accounts/logout/">
                            Log out
                        </a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <!-- Button trigger modal -->
                    <a role="button" class="btn btn-primary" data-toggle="modal" data-target="#loginModal">
                        Log In
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loginModalLabel"><i class="fas fa-sign-in-alt"></i> &nbsp;&nbsp;Log In</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <a role="button" class="btn btn-outline-dark btn-block btn-sm"
                           href="{% provider_login_url 'google' %}">
                            <i class="fab fa-google"></i> &nbsp;&nbsp;Log in with Google
                        </a>
                        <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="/accounts/login/">
                            <i class="far fa-envelope"></i> &nbsp;&nbsp;Log in with E-mail
                        </a>
                    </div>
                    <div class="col-md-6">
                        <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="/accounts/signup/">
                            <i class="far fa-envelope"></i> &nbsp;&nbsp;Sign Up with E-mail
                        </a>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>